### ISSUE TITLE
Maybe not use dev version of hydra would be better!

### ISSUE THREAD

**Issue by LuoXin-s** [ashleve/lightning-hydra-template#101]
I noticeed that there are rc and dev versions of hydra in requirement.txt. Not use unstable lib for development may be better. Is there any new features of dev/rc branch  in the template?

**Comment by hobogalaxy** [comment]
@sfasdas yes, there are a couple of features available in development version only, which are currently used by the template: [experiment configurations](https://hydra.cc/docs/next/patterns/configuring_experiments), [optuna sweeper](https://hydra.cc/docs/next/plugins/optuna_sweeper), and a few minor changes.

According to Hydra developers, v1.1 will be released soon (I'd expect it in the next 1-2 months), so we should be able to play with dev version comfortably.
The only issues I spotted so far was that installation of [tab completion](https://hydra.cc/docs/next/tutorials/basic/running_your_app/tab_completion) doesn't work for me.
