### ISSUE TITLE
Multi-GPU training on DDP mode will log multiple times

### ISSUE THREAD

**Issue by LuoXin-s** [ashleve/lightning-hydra-template#115]
I notice when I use `+trainer.accelerator="ddp"`, the log file have **repeated logs**(The number of repeats is equal to the number of GPUs), refer to [official docs](https://pytorch-lightning.readthedocs.io/en/latest/advanced/multi_gpu.html#distributed-data-parallel), **"Lightning implementation of DDP calls your script under the hood multiple times with the correct environment variables:"**.
So we need a solution to handle this problem since DDP mode is much faster than DDP_spawn.

**Comment by LuoXin-s** [comment]
And also repeated error log, that's confusion for debug in sometimes.

**Comment by hobogalaxy** [comment]
@LuoXin-s PyTorch-Lightning uses the `rank_zero_only` function to ensure that some actions are only performed by the process with rank 0.

You could try to apply it for python logger and config printing.

**Comment by dekura** [comment]
Hi, @LuoXin-s @ashleve temporarily I add `@rank_zero_only` to the 3 functions in `template_utils.py`.
The config print only once, and the logging info looks much better now.

```python
from pytorch_lightning.utilities import rank_zero_only


...

@rank_zero_only
def extras(config: DictConfig) -> None:
    """A couple of optional utilities, controlled by main config file.
        - disabling warnings
        - disabling lightning logs
        - easier access to debug mode
        - forcing debug friendly configuration
    Args:
        config (DictConfig): [description]
    """


@rank_zero_only
def print_config(
    config: DictConfig,
    fields: Sequence[str] = (
        "trainer",
        "model",
        "optimizer",
        "datamodule",
        "callbacks",
        "logger",
        "seed",
    ),
    extra_depth_fields: Sequence[str] = (
        "callbacks",
        "logger",
    ),
    resolve: bool = True,
) -> None:


@rank_zero_only
def log_hyperparameters(
    config: DictConfig,
    model: pl.LightningModule,
    datamodule: pl.LightningDataModule,
    trainer: pl.Trainer,
    callbacks: List[pl.Callback],
    logger: List[pl.loggers.LightningLoggerBase],
) -> None:



```

**Comment by ashleve** [comment]
@dekura Thanks!
I believe the logs from src/train.py would still be doubled though.
There's a `rank_zero_logger` branch containing wrapper for python logger, that's supposed to take care of that. It's available here:
https://github.com/ashleve/lightning-hydra-template/blob/1165753e48bd97cc9a2a6cd05b9bde59e50fea85/src/utils/template_utils.py#L19-L36

**Comment by dekura** [comment]
@ashleve Thanks!

Actually I tried the `RankZeroLogger()`, I replace all the `hydra.util.log` to `RankZeroLogger()`, but all the config will still print multi-times.  So the combination with the `RankZeroLogger()` and my suggesstion below will make the printed information prettier.

> Hi, @LuoXin-s @ashleve temporarily I add `@rank_zero_only` to the 3 functions in `template_utils.py`.
> The config print only once, and the logging info looks much better now.
> 
> ```python
> from pytorch_lightning.utilities import rank_zero_only
> 
> 
> ...
> 
> @rank_zero_only
> def extras(config: DictConfig) -> None:
>     """A couple of optional utilities, controlled by main config file.
>         - disabling warnings
>         - disabling lightning logs
>         - easier access to debug mode
>         - forcing debug friendly configuration
>     Args:
>         config (DictConfig): [description]
>     """
> 
> 
> @rank_zero_only
> def print_config(
>     config: DictConfig,
>     fields: Sequence[str] = (
>         "trainer",
>         "model",
>         "optimizer",
>         "datamodule",
>         "callbacks",
>         "logger",
>         "seed",
>     ),
>     extra_depth_fields: Sequence[str] = (
>         "callbacks",
>         "logger",
>     ),
>     resolve: bool = True,
> ) -> None:
> 
> 
> @rank_zero_only
> def log_hyperparameters(
>     config: DictConfig,
>     model: pl.LightningModule,
>     datamodule: pl.LightningDataModule,
>     trainer: pl.Trainer,
>     callbacks: List[pl.Callback],
>     logger: List[pl.loggers.LightningLoggerBase],
> ) -> None:
> ```

**Comment by ashleve** [comment]
@dekura yess, will upgradee the main branch soon with all the rank zero logging.

@LuoXin-s 
> And also repeated error log, that's confusion for debug in sometimes.

I don't know if there's any way to prevent that but I believe it should work that way - each gpu process should print its own error since in some cases they can be unrelated to each other.
Ignoring errors from processes other than rank zero could potentially discard important info for debuging

**Comment by ashleve** [comment]
@dekura I think `def extras(config: DictConfig)` shouldn't be marked as rank zero since it modifies the config - this can lead to different configurations on different processes. 
Also I see you're using outdated versions of those methods, you might want to update `template_utils.py` to the one from main branch.

**Comment by dekura** [comment]
@ashleve You are right, and I will update the code to the latest version.
BTW, Thank you for your elegent code.

**Comment by ashleve** [comment]
Rank zero improvements merged.
