### ISSUE TITLE
TF2.0 template

### ISSUE THREAD

**Issue by zakajd** [ashleve/lightning-hydra-template#116]
Hi!
Thanks for an awesome work
I wanted to ask, if there is anything similar to this template but for TF2.0 + Hydra bundle?
Didn't manage to find anything relevant on the GitHub

Best regards

**Comment by hobogalaxy** [comment]
@zakajd I don't know of any such project. Feel free to create your own version if you want to base it on this template.

**Comment by andrewjong** [comment]
Yeah, there's nothing quite like Lightning for TensorFlow 2 that I know of.
