### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by elisim** [ashleve/lightning-hydra-template#122]
Hi,

Thank you for the awesome repo. Unfortunately, the following links are broken:

https://github.com/ashleve/lightning-hydra-template/blob/6a15f8ef3bd34a167743a0c046dc9a35449c5aaf/src/datamodules/mnist_datamodule.py#L17

https://github.com/ashleve/lightning-hydra-template/blob/6a15f8ef3bd34a167743a0c046dc9a35449c5aaf/src/models/mnist_model.py#L22

Thank you,
Eli

**Comment by ashleve** [comment]
@elisim Hi,
thank you for reporting. The links are fixed now.
