### ISSUE TITLE
Remove WANDB_START_METHOD: thread

### ISSUE THREAD

**Issue by somedadaism** [ashleve/lightning-hydra-template#126]
In a [related issue](https://github.com/facebookresearch/hydra/issues/1553) of hydra I found out that setting `WANDB_START_METHOD: thread` is no longer required for hydra sweeps and it also affects hydra logging.
If you can confirm that the environment variable has become unnecessary I propose it would be an enhancement to remove it from the configuration. Also thank you for the great template. 👍

**Comment by ashleve** [comment]
Thanks! Will remove it after conducting some tests.
