### ISSUE TITLE
Custom Callbacks

### ISSUE THREAD

**Issue by sirtris** [ashleve/lightning-hydra-template#127]
hi,
I am trying to write a custom callback.
Where and how does the callback object actually get instantiated? 
Or more specifically how can I pass arguments to the callback?

My callback looks like this:
```python
class ImagePredictionLogger(Callback):
    def __init__(self, val_samples, num_samples=32):
        super().__init__()
        self.num_samples = num_samples
        self.val_imgs, self.val_labels = val_samples

    def on_validation_epoch_end(self, trainer, pl_module):
        ...
```

When I run the code I get:
`TypeError: Error instantiating 'src.callbacks.wandb_callbacks.ImageLogger' : __init__() missing 1 required positional argument: 'val_samples'`

Which I guess makes sense but how can I pass the argument to the callback?
Thanks

**Comment by ashleve** [comment]
@sirtris Hi,
the callbacks are instantiated here:
https://github.com/ashleve/lightning-hydra-template/blob/e27c11c34254f435cfb5c8f6ab7b7f747020621a/src/train.py#L38-L44

From your example I'm guessing that `val_samples` are example images. Those can't be specified inside yaml config file but you have a couple of other options:
1. Access images from validation dataloader inside callback:
```python
    def on_validation_epoch_end(self, trainer, pl_module):
        val_dataloaders = trainer.val_dataloaders
        ...
```
2. Somehow pass `val_samples` inside [train.py](https://github.com/ashleve/lightning-hydra-template/blob/main/src/train.py), for example:
```python
# add method for setting val_samples to your callback
def set_samples(val_samples):
    self.val_samples = val_samples
```

```python
# in train.py
for cb in callbacks:
    if isinstance(cb, ImagePredictionLogger):
        cb.set_samples(val_samples)
```

3. Somehow hardcode image examples inside the callback or store them in data file loaded by callback, so you don't need to pass `val_samples` parameter on initialization

**Comment by ashleve** [comment]
Btw it would be great to add a generic WandbImageLogger callback to the ones available in wandb_callbacks.py (which I think should use the number 1 approach for simplicity). If you would like to feel free to make a PR!

**Comment by sirtris** [comment]
Thanks for the tips. 
I'll look into it and make a PR when I get it to work as intended.
