### ISSUE TITLE
Is resume ckpt not resume logger solved?

### ISSUE THREAD

**Issue by vpeopleonatank** [ashleve/lightning-hydra-template#128]
I 've seen this PR on pytorch-lightning repo, is this problem solved? https://github.com/PyTorchLightning/pytorch-lightning/pull/5931

**Comment by ashleve** [comment]
@vpeopleonatank Hi, 
I'm pretty sure the issue you linked has been already solved, hovewer it doesn't have anything to do with resuming logger when resuming training from checkpoint.

Resuming loggers on ckpt has never been in lightning before, but it will be added in the future, currently scheduled for release 1.4.
You can track a progress here: https://github.com/PyTorchLightning/pytorch-lightning/pull/6361

If you need to you can resume wandb logger state by yourself, by setting the id parameter:
```
python run.py trainer.resume_from_ckpt=path/to/ckpt/ logger=wandb logger.wandb.id=ujh18721
```
You can find the id in the link of the run you want to resume:
![image](https://user-images.githubusercontent.com/43458894/115681884-3ca62080-a355-11eb-8dea-5e7f6ab10753.png)

**Comment by vpeopleonatank** [comment]
Thanks for clarification. :handshake:
