### ISSUE TITLE
adding a linter

### ISSUE THREAD

**Issue by elisim** [ashleve/lightning-hydra-template#140]
Hi,

Thank you for the great work.
Do you consider adding `pylint` to this template?

It might be really useful. 

Thank you

**Comment by ashleve** [comment]
Hi,

I'm definitely open to adding new linters.
I'm not very knowledgable in that area though.
Could you explain why pylint is good addition for exactly this template? what would be the benefits?

I'm also considering flake8 and yapf

**Comment by elisim** [comment]
Thank you for your response.

From my knowledge, pylint might be a better choice for a linter, because it's popularity:

![image](https://user-images.githubusercontent.com/17675462/118390706-2ed47a00-b639-11eb-82d4-5fe09e8588dd.png)

Although I saw projects that use both (e.g. [bentoml](https://github.com/bentoml/BentoML))

See also: [Any advantages of Flake8 over PyLint?](https://www.reddit.com/r/Python/comments/82hgzm/any_advantages_of_flake8_over_pylint/)

> Could you explain why pylint is good addition for exactly this template? what would be the benefits?

I think that pylint with a minimal configuration might even increase the researchers productivity who use this template. For example, the minimal addition will be in `.pre-commit` config:

```yaml
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
```

Thank you again for the great work!

**Comment by ashleve** [comment]
@elisim Thanks for the detailed explanation!

After trying out pylint I feel like it does too much. It doesn't work with the template out of the box - you would need to also disable many error codes in `setup.cfg`. For example, pylint doesn't localize the imports correctly in the template unless you specify the absolute path to the project.
![image](https://user-images.githubusercontent.com/43458894/118571435-52550d00-b77e-11eb-9a58-987018146d6c.png)

Here's a part of 200+ pylint errors I got when running it on the template:
![image](https://user-images.githubusercontent.com/43458894/118571182-bcb97d80-b77d-11eb-9ddd-85fe1db7f06c.png)

It seems to me there's more of a loss in productivity than gain - most of the detected errors are desired or can't really be fixed, which means you often loose time on explicitly disabling them in `setup.cfg`.

On the other hand, flake8 is less powerful but works out of the box with just pre-commit hook.

If you still find pylint more productive though, please prove me wrong

**Comment by ashleve** [comment]
Release v0.9 adds support for flake8 and auto yaml formatting with prettier
