### ISSUE TITLE
trainer `ddp.yaml` doesn't override `default.yaml`?

### ISSUE THREAD

**Issue by thomas-happify** [ashleve/lightning-hydra-template#145]
Hi there, 

This template is awesome, and I'm running some examples with it right now.

In `configs/config.yaml`, I changed 
```
...
# specify here default training configuration
defaults:
  - trainer: default.yaml
...
 ```

but when I call `python run.py trainer.gpus=4 trainer=ddp` it only runs `ddp.yaml` configs without overriding the `default.yaml`.

Is this behavior expected? because when I'm reading [`lightning-transformer`](https://github.com/PyTorchLightning/lightning-transformers#enable-sharded-training) , by passing `trainer=sharded`, it actually overwrites the `default.yaml` like
```
trainer:
-  gpus: null
+  gpus: 1
   auto_select_gpus: false
   tpu_cores: null
   log_gpu_memory: null
   ...
   log_every_n_steps: 50
-  accelerator: null
+  accelerator: ddp
   sync_batchnorm: false
-  precision: 32
+  precision: 16
   weights_summary: top
   ....
   terminate_on_nan: false
   auto_scale_batch_size: false
   prepare_data_per_node: true
-  plugins: null
+  plugins:
+    _target_: pytorch_lightning.plugins.DDPShardedPlugin
   amp_backend: native
   amp_level: O2
   move_metrics_to_cpu: false
...
```

**Comment by ashleve** [comment]
Hi, 
yes this was intentional, 
you can easily achieve the other behavior by adding inheritence from default.yaml to ddp.yaml:
```yaml
defaults:  
    - default.yaml # add args from default trainer conf

gpus: 4
accelerator: ddp
```
my reason for not inheriting was that I don't like having all of the 40+ parameters from default printed in terminal at the beginning of the run, I like to see only the relevant ones.

Although now that you mentioned it, I think the iheritence might be a better approach and I will probably change it to something like this:
```
trainer/
    ├── default.yaml         <- a couple of default args specific for given project
    ├── all_params.yaml      <- all parameters of the trainer
    ├── ddp.yaml             <- inherits from defualt.yaml
    ├── sharded.yaml         <- inherits from defualt.yaml
    ├── debug.yaml           <- inherits from defualt.yaml
    ├── ...
```

**Comment by thomas-happify** [comment]
@ashleve 
yes I agree, that's one of the main advantages of using hydra yaml.

btw, for wandb sweep, I think I found a work around, but I don't know if it's behaving correctly, so I would like ur input.
Let me comment in this previous thread https://github.com/ashleve/lightning-hydra-template/issues/58  to continue
