### ISSUE TITLE
Resubmit on slurm environment

### ISSUE THREAD

**Issue by zhengzangw** [ashleve/lightning-hydra-template#146]
I run experiments on a slurm environment with a time limit. I want to re-submit my job if it is not completed. [Pytorch Lightning](https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster.html) handles this by reload the weight. I test the code in this repo but find that resubmit on slurm is not supported.

I wonder how to enable resubmit in slurm environment. This is a great repo and I hope it can be further improved.

Thanks in advance.

**Comment by zhengzangw** [comment]
I found that in my two runs log dir: `logs/runs/2021-06-01/12-11-19/` and `logs/runs/2021-06-01/12-05-19/`, both contain a `hpc_ckpt_1.ckpt` file. I think the reason why re-submit failed is that in a re-run, a new experiment log dir is created and the program cannot detect the original one.

**Comment by ashleve** [comment]
Hi, thanks for reporting. 
Unfortunately for now I'm not really familiar with SLURM so I won't be much help.
Perhaps you could report it on lightning repo? 
There has been a number of incompatibility issues between lightning and hydra which the devs have already fixed.

**Comment by zhengzangw** [comment]
I find the way to make it work! Set arguments `weights_save_path` to a absolute path and it can reload correctly.

I also find that the pytorch lightning team is working to make the logger (wandb, comet-ml) resume logging. https://github.com/PyTorchLightning/pytorch-lightning/issues/6205

**Comment by ashleve** [comment]
Nice but I think lightning could handle this without such workarounds, perhaps they're just not aware of the issue.

Btw, I'm the one who has been implementing the logger resuming feature, you can find the PR here: https://github.com/PyTorchLightning/pytorch-lightning/pull/6361
Unfortunately it's currently on hold because of the proposition to redesign Logger class: https://github.com/PyTorchLightning/pytorch-lightning/issues/6606

**Comment by zhengzangw** [comment]
Wow, that's a coincidence. Thanks for your contribution again. I have submitted a discussion on PyTorch lighting: https://github.com/PyTorchLightning/pytorch-lightning/discussions/7804.
