### ISSUE TITLE
is it possible to loop through wandb sweep?

### ISSUE THREAD

**Issue by thomas-happify** [ashleve/lightning-hydra-template#154]
Hi @ashleve ,

I'm wondering if it's possible to loop through sweeps.

For example, I have 2 datasets: A, and B.
according to ur solution [here](https://github.com/ashleve/lightning-hydra-template/issues/58#issuecomment-852337163)
I must sweep these 2 dataset individually by launching 2 wandb agents.

Is there any workaround where I can just call `wandb sweep <config.yaml>` once, and it will sweep these 2 datasets sequentially?

Thanks for your help!

**Comment by ashleve** [comment]
@thomas-happify Hi, sorry for late response,
what I would do is to just prepare 2 different configs for hyperparameter search, and then schedule 2 sweeps for a certain amount of runs, using a bash script:
```bash
wandb agent --count 20 rfqmq58a
wandb agent --count 20 dsfaws31
```
feel free to reopen if you have any questions or if you found a better way
