### ISSUE TITLE
How to disable hydra logging if run with debug=True?

### ISSUE THREAD

**Issue by brijow** [ashleve/lightning-hydra-template#155]
Not sure how to achieve this -- in the utils.py file, I see you are modifying the config object, but I am not sure how we can control the hydra configuration if run with debug flag since it is deleted from the config by hydra automatically.

**Comment by ashleve** [comment]
Not sure if this is possible, I believe the logging folders are created the moment `@hydra.main` method is called, so modifying config afterwards won't help here. Perhaps it could be done with the new [callbacks interface](https://hydra.cc/docs/experimental/callbacks). 

Will investigate the possibilites.

**Comment by ashleve** [comment]
@brijow I don't see a way to disable logging but how about logging into different folder when in debug mode? I believe logs can be still useful when debugging.

For example:
```
logs/
    debug/
    runs/
    multiruns/
```

We could introduce a config group which overwrites the logging path when in debug mode:
```
python run.py mode=debug
```

debug.yaml:
```yaml
# @package _global_

debug: true

hydra:
  run:
    dir: logs/debug/${now:%Y-%m-%d}/${now:%H-%M-%S}
```

Would be useful to also have experiment mode, for when you want a folder with specific name, for example:
```
python run.py mode=experiment name="some_experiment_name"
```
experiment.yaml:
```yaml
# @package _global_

name: ???

hydra:
  run:
    dir: logs/experiments/${name}
```


Will probably introduce this in next release.

**Comment by brijow** [comment]
I like it, especially running with an experiment name flag to save to specific folder. I am currently doing basically the same thing to achieve the debug functionality, but rather than log to a different folder I was disabling logging like so:


```
# @package _global_

defaults:
  - override /hydra/hydra_logging: disabled
  - override /hydra/job_logging: debug    # debug job logging prints to cli with custom message, but not very important tbh
  - override /hydra/callbacks: debug        # disable some callbacks, e.g. do not push to s3 when run finishes

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
```


I think hydra logging can be a little annoying at times, so I'd personally keep an option to disable it if needed, but I like the idea of having multiple logging folders depending on what you're doing, debugging, experiment logging, etc.

**Comment by ashleve** [comment]
Kind of late but different running modes are added now
