### ISSUE TITLE
Add an image classification example preferably using timm and a imagenet/folders dataloader

### ISSUE THREAD

**Issue by kurtjcu** [ashleve/lightning-hydra-template#157]
Add an image classification example preferably using timm and a imagenet/folders dataloader

**Comment by ashleve** [comment]
Would prefer not adding another model to keep template simple. You would need to delete a lot of files when starting a new project. Although if you would like to create this example in your own repo I would be willing to reference it in the readme under "examples" section

**Comment by kurtjcu** [comment]
fair enough. :)
