### ISSUE TITLE
How to load configurations of the previous experiment?

### ISSUE THREAD

**Issue by marsggbo** [ashleve/lightning-hydra-template#159]
Say I have run multiple experiments and each saves `config.yaml`, `hydra.yaml`, and `overrides.yaml`. Now I want to rerun the best one. It seems that the config path is fixed in `run.py`, so I wonder there is an easy way to reload the specified configurations without need to modify `run.py`?

**Comment by ashleve** [comment]
You can override the used config with:
```
python run.py --config-path /logs/runs/.../.hydra --config-name config.yaml 
```
The command line overrides are already contained in config.yaml. 
The problem is config.yaml does't contain the hydra configuration, which means the logs output directory will change to default. I don't really see a workaround for that.

**Comment by marsggbo** [comment]
thanks. can we just simply manually copy the content of `hydra.yaml` to `config.yaml`? 😂 or maybe we can modify the saving mode, i.e., saving hydra and config into the same yaml file.

**Comment by ashleve** [comment]
I don't know if saving into the same file is possible but manually coping hydra config paths should definitely work
