### ISSUE TITLE
get_wandb_logger fails to retrieve WandbLogger when debug=True

### ISSUE THREAD

**Issue by ChristianHinge** [ashleve/lightning-hydra-template#160]
Firstly, I love this repo - really great job!!
Maybe this not really a bug, but more of a "watch out for this"-kinda thing, which can be documented somewhere in the README. 

Error:
`Exception: You are using wandb related callback, but WandbLogger was not found for some reason...`
This error occures when calling the function `src.callbacks.wandb_callbacks.get_wandb_logger()`. 

How to reproduce:
1. Clone repo
2. `python run.py debug=True logger=wandb callbacks=wandb`

Relevant information
`pytorch_lightning==1.4.0`

The problem
When setting `debug=True`, the Trainer is passed `fast_dev_run=True`. 
In this mode, pytorch_lightning disables all logger(s), which causes `get_wandb_logger()` to fail. 
https://pytorch-lightning.readthedocs.io/en/latest/common/debugging.html 
Upon inspection of the trainer object. The trainer.logger is of type `pytorch_lightning.loggers.base.DummyLogger`, which I assume is the placeholder logger that lightning uses with `fast_dev_run=True`. 
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.base.html#pytorch_lightning.loggers.base.DummyLogger

I assume this is one of the reasons you have made a debug.yaml which uses `fast_dev_run=False`. My suggestion is to mention this as an option in the debugging section of the README.

**Comment by ashleve** [comment]
@ChristianHinge Thanks! I think it might be easier to just add a more explicit exception message to `get_wandb_logger()` since it requires only a simple check:
```python
if trainer.fast_dev_run:
    raise Exception("Cannot use wandb callbacks since pytorch lightning disables loggers in debug mode.")
```
