### ISSUE TITLE
Conda setup script failes for CUDA11.1

### ISSUE THREAD

**Issue by chuber1986** [ashleve/lightning-hydra-template#162]
Installing cudatoolkit=11.1 requires adding '-c nvidia'. See https://pytorch.org/get-started/locally/

I suggest the following addition:
`
# Install pytorch
if [ "$cuda_version" == "none" ]; then
    conda install -y pytorch=$pytorch_version torchvision torchaudio cpuonly -c pytorch
elif [ "$cuda_version" == "10.2" ]; then
    conda install -y pytorch=$pytorch_version torchvision torchaudio cudatoolkit=$cuda_version -c pytorch
else
    conda install -y pytorch=$pytorch_version torchvision torchaudio cudatoolkit=$cuda_version -c pytorch -c nvidia
`

BR Christian

ps. The template is awesome! ;)

**Comment by ashleve** [comment]
@chuber1986 Thanks, I will take a look into that
