### ISSUE TITLE
[Help wanted!!]When outputs redirect from terminal to a log file, Progress Bar will output in new line but update original line

### ISSUE THREAD

**Issue by LuoXin-s** [ashleve/lightning-hydra-template#165]
like this:
![image](https://user-images.githubusercontent.com/20135317/129651087-e005fcb5-72a6-4d8d-8248-5164ce621f64.png)

My log file is full of this progress bar!

**Comment by LuoXin-s** [comment]
Desired behavior dynamic refresh in one line or just print once every epoch end.

**Comment by ashleve** [comment]
I'm don't know if there's any way to prevent that. You should probably make issue in pytorch lightning repository

**Comment by LuoXin-s** [comment]
> I don't know if there's any way to prevent that. You should probably make issue in pytorch lightning repository

Ok, thinks, I'll make a issue in lightning's repository.
