### ISSUE TITLE
Add optuna.integration.PyTorchLightningPruningCallback

### ISSUE THREAD

**Issue by LaurenzBeck** [ashleve/lightning-hydra-template#176]
Great Project template ❤️ , I am loving your code-style and I am really looking forward to other data-scientists adopting more standards like you do.

I really like hydras multirun feature with the optuna sweeper, but unfortunately your template does not make use of the official Pruning Callback, which can dramatically speed up the tuning process by monitoring runs and skipping poorly performing ones.

The only problem is, that the callback requires a reference to the current trial object to call `trial.report(current_score, step=epoch)` and `trial.should_prune()`, to ultimately raise `optuna.TrialPruned(message)` for the actual pruning.

I think this template would greatly benefit from also including this callback.

**Comment by ashleve** [comment]
Thanks for the feedback!

The thing is, as far as I'm aware, we don't have access to the trial object since it is managed by Optuna plugin for Hydra - I don't see a way to tackle this issue in the template as long as the feature is not somehow supported by the plugin.

You could ask about it on Hydra repo

**Comment by LaurenzBeck** [comment]
I see :)

I already wrote them and will forward any news from them to this thread.

Kind regards,
Laurenz

Łukasz Zalewski ***@***.***> schrieb am Mo., 27. Sep. 2021,
14:55:

**Comment by LaurenzBeck** [comment]
Apparently, there is no general/elegant way to access variables/objects of the main node from a launched job.
(referring to the hydra - multirun - launcher - sweeper interaction).
There might be a hack/workaround for a specific configuration (e.g. using the local launcher), but that is of no interest to the hydra supporters (and I can understand this choice.)
I am currently aiming for a separation of run and tune script that manually creates an optuna study from a hydra configuration.
I think while this is a bit of extra work, this approach is cleaner and simpler to get into, because you can use all of optuna's features in the intended and documented way.

But still this is very sad, because I really liked the multirun feature of hydra...

**Comment by MartinSmeyer** [comment]
FYI: https://github.com/facebookresearch/hydra/issues/1710#issuecomment-932160664
