### ISSUE TITLE
Enanche debug mode

### ISSUE THREAD

**Issue by gscriva** [ashleve/lightning-hydra-template#177]
First of all I really appreciate this template, awesome!

I have a suggestion on the debug mode. In particular there is a typo in the first point of the [Easily Debug](https://github.com/ashleve/lightning-hydra-template#your-superpowers), i.e., `python run.py trainer.fast_dev_run=true`  should be `python run.py +trainer.fast_dev_run=true`.

Moreover, I would suggest putting (almost) all together in `configs/trainer/debug.yaml`, so one can simply run `python run.py trainer=debug` in order to enable some debug features as shown below:
```
defaults:
  - default.yaml

gpus: 0

min_epochs: 1
max_epochs: 2

# prints
progress_bar_refresh_rate: null
weights_summary: "full"
profiler: "simple"

# debugs
fast_dev_run: true
num_sanity_val_steps: 2
overfit_batches: 0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
track_grad_norm: -1
terminate_on_nan: true
```

Or maybe we can restore the flag `debug` in [configs/config.yaml](https://github.com/ashleve/lightning-hydra-template/blob/86f30fb32081ae03166e515210b9cfb9e2952e91/configs/config.yaml) and set the debug options [here](https://github.com/ashleve/lightning-hydra-template/blob/86f30fb32081ae03166e515210b9cfb9e2952e91/src/utils/utils.py#L50).

First issue for me on GitHub, so don't be too rude ;)

**Comment by ashleve** [comment]
Hi! Thanks for the suggestions, make a lot of sense ;)

The reason for removing debug flag was that I felt like it's getting confusing when there's already a debug logging mode, debug trainer, and debug flags in the trainer, so I think it would be better to go with enabling some options  by default in debug trainer as you suggest

Would you like to make a PR?
