### ISSUE TITLE
Including template license file in projects

### ISSUE THREAD

**Issue by AlexHarn** [ashleve/lightning-hydra-template#178]
Hi!

How would you like/recommend the template's license file to be included in projects based on the template? I think the LICENSE file in the main directory should be used for the project that is based on the template, but obviously we want to honor the template's MIT license as well. Should we maybe include it at the end of the project's README under acknowledgements?

**Comment by ashleve** [comment]
Hi! Thanks for the question, 

I kind of haven't thought about it before, but if this repo is used for generating other projects, then the template license file shouldn't be placed along with other files, so users don't accidentally give away permissions to their IP without intentionally doing so. I will move it to README as you suggest.

If you're wondering whether you should smh acknowledge the template/license in your own project, then do however you want, I really don't mind

**Comment by AlexHarn** [comment]
Thanks! I'll just add the reference under acknowledgements in my README then.
