### ISSUE TITLE
access hydra parent configuration from child

### ISSUE THREAD

**Issue by faroit** [ashleve/lightning-hydra-template#182]
Under some circumstances it might be necessary to access e.g. the datamodules configuration (`config.datamodule`) from inside the model code (e.g. to dynamically create certain models based on different data configuration....)

what would be the simplest and most recommended way to access the parent `config` object from within a child config?

**Comment by ashleve** [comment]
You have a couple of options.

1. Pass additional parameter on model generation:
```python
model: LightningModule = hydra.utils.instantiate(config.model, some_param=config.datamodule.some_param)
```

2. Attach part of the datamodule config to model config:
```yaml
model:
    some_param: ${datamodule.some_param}
```

3.  Access datamodule attributes in model (see [#Tricks](https://github.com/ashleve/lightning-hydra-template#tricks))

<br>

I will leave it to you to choose which one is the most convenient

**Comment by faroit** [comment]
@ashleve that's excellent. (3.) seems to be the most convenient. Sorry for not having read the tricks section...
