### ISSUE TITLE
Is it possible to log experiment path to wandb?

### ISSUE THREAD

**Issue by Steve-Tod** [ashleve/lightning-hydra-template#183]
Hi, thank you for your great repo! 

I'm just wondering if it's possible to log the experiment path on wandb info page so that I can quickly trace the checkpoint and config for each run.

**Comment by ashleve** [comment]
Hi,
easiest way is to just save current working directory as a hyperparameter [here](https://github.com/ashleve/lightning-hydra-template/blob/e34ccb0acfb36381ce3cf7f6b7b9bf0ae85bf936/src/utils/utils.py#L132-L140)

There are also callbacks in the template which allow you to upload all checkpoints and config files directly into the wandb run

**Comment by Steve-Tod** [comment]
Thank you!
