### ISSUE TITLE
[get_logger] What is a good way to set logging level as a hydra parameter?

### ISSUE THREAD

**Issue by CharlesGaydon** [ashleve/lightning-hydra-template#186]
I call the following function at the beginning of my scripts to get a (text) logger :
```python
# src.utils.py
def get_logger(name=__name__, level=logging.INFO) -> logging.Logger:
    """Initializes multi-GPU-friendly python logger."""

    logger = logging.getLogger(name)
    logger.setLevel(level)

    # this ensures all logging levels get marked with the rank zero decorator
    # otherwise logs would get multiplied for each GPU process in multi-GPU setup
    for level in (
        "debug",
        "info",
        "warning",
        "error",
        "exception",
        "fatal",
        "critical",
    ):
        setattr(logger, level, rank_zero_only(getattr(logger, level)))

    return logger
```

```python
# src/other_script.py
from src.utils import utils
log = utils.get_logger(__name__)
...
log.info(...)
```

I would like to create a hydra parameter somewhere to control for the level of debugging info I print without having to manually edit it (for example: switching from `level=logging.INFO` to `level=logging.DEBUG`). 

I assume there is an easy solution, but I am still unfamilliar with the possibilities of Hydra. Would you know how to do it?

Maybe having a `logging_level` parameter in `configs/configs.yaml` would be a useful addition to this (already so great and complete) template :)

**Comment by ashleve** [comment]
@CharlesGaydon It's already built-in hydra, check this out:
https://hydra.cc/docs/tutorials/basic/running_your_app/logging/

After reading your issue I updated the template as I realized the `logger.setLevel(level)` should not be present in `get_logger()` method to enable switching logging mode by hydra. Take a look at the changes here: https://github.com/ashleve/lightning-hydra-template/commit/eee3f9ccd32139ff9b33b246080358f01582a385
Please update your project accordingly.

Now the `DEBUG` level is automatically enabled when using `python run.py mode=debug`
You can also enable the `DEBUG` level by using hydra built-in config option:
```
python run.py hydra.verbose=true
```
You can also set `DEBUG` level for only chosen loggers:
```
python run.py hydra.verbose=[src.train, src.utils.utils]
```
