### ISSUE TITLE
Multi run mode skips the testing part when using DDP

### ISSUE THREAD

**Issue by zhiyuanpeng** [ashleve/lightning-hydra-template#194]
I can run `--multirun +experiment=exp1, exp2, exp3`, but when the `exp1` is loading the saved checkpoint to test, the second `exp2` is started, and then the process freezes at the beginning of `exp2`. How to solve this problem? Thanks.

**Comment by zhiyuanpeng** [comment]
DDP with multi run doesn't work

**Comment by ashleve** [comment]
All DDP discussions are moved to https://github.com/ashleve/lightning-hydra-template/issues/393
