### ISSUE TITLE
Examples on model test and predicton.

### ISSUE THREAD

**Issue by ahahahahawd** [ashleve/lightning-hydra-template#200]
Can you gave some examples on test and predict using config yaml like train/test/demo/ xx.yaml? Thx!

**Comment by sounakdey** [comment]
Please some examples just on test.py will be great

**Comment by ashleve** [comment]
@ahahahahawd  @sounakdey  The template now contains example separate testing pipeline. Introduced with https://github.com/ashleve/lightning-hydra-template/pull/250
