### ISSUE TITLE
Passing hyperparameter from src.datamodules.xxx_model.xxxModel to src.datamodules.xxx_datamodule.xxxDataModule

### ISSUE THREAD

**Issue by ihamdi** [ashleve/lightning-hydra-template#201]
I'm working on SIIM-FISABIO-RSNA COVID-19 Detection competition on Kaggle and the data needs to be processed differently according to the model used. For example, torchvision.models.densenet121 expects a 3-channel array while torchxrayvision.models.DenseNet expects a 1-channel array (which is what the x-ray dicom format gives anyways). Because of that, I'm having to pass the model name to both the datamodule as well as the model in order to make things work.

How would you recommend approaching that in order to avoid duplicating inputs on the config files?

Thank you for your wonderful work. This repo is going to be immensely helpful to the project I'm trying to do.

**Comment by vmichals** [comment]
omegaconf, which hydra is built upon, supports [variable interpolation](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#variable-interpolation), so you could have something like this in your _configs/datamodule/xxx_datamodule.yaml_:
```input_format: ${model.input_format}```
which fetches the value of `input_format` from your model's yaml config.

**Comment by ihamdi** [comment]
Thank you very much for the quick response. I will give it a try right away.

> omegaconf, which hydra is built upon, supports [variable interpolation](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#variable-interpolation), so you could have something like this in your _configs/datamodule/xxx_datamodule.yaml_: `input_format: ${model.input_format}` which fetches the value of `input_format` from your model's yaml config.
