### ISSUE TITLE
"You called `self.log({name},...)` twice in `{fx}` with different arguments. This is not allowed"

### ISSUE THREAD

**Issue by ihamdi** [ashleve/lightning-hydra-template#202]
I'm getting this message on some runs which is strange since the only thing changing is the model name inside the experiment config files.

I haven't touched the training step so I'm not sure how the self.log in the is being called twice. Non of my colleagues have encountered this error, but non of them are using the latest update either. I just started using lightning last week so I'm running on 1.2.

[https://drive.google.com/file/d/1dqEqZE8yvWDVT2xeYPSAMq_aOnxOofb2/view?usp=sharing](url)

**Comment by ashleve** [comment]
If I understood correctly, you're using pytorch lightning v1.2? Is there a reason for using older version? The template is currently compatible only with v1.5

Btw. the access to google drive link is blocked

**Comment by ihamdi** [comment]
> If I understood correctly, you're using pytorch lightning v1.2? Is there a reason for using older version? The template is currently compatible only with v1.5
> 
> Btw. the access to google drive link is blocked

Sorry about the Google Drive link. Not sure why its locked. Here's a new one https://drive.google.com/file/d/1dqEqZE8yvWDVT2xeYPSAMq_aOnxOofb2/view?usp=sharing

I apologize for the confusion. I meant Pytorch Lightning 1.5. It seems like it was released 13 days ago.

**Comment by ashleve** [comment]
Lightning 1.5 introduces a couple of backward incompatible changes. I also don't know what causes your problem, but please update to newer version if it's possible - the template is not compatible with previous versions.

Btw. you can just paste the screenshot directly into the message instead of sharing on google drive

**Comment by Gxinhu** [comment]
Hi there, I think I have met this problem before.  If your problem is the same as I met, just update your pytorch lighting to the latest version >=1.5.1, and the problem is caused by RichProgressBar on 1.5.0.
