### ISSUE TITLE
"Accessing datamodule attributes in model" Trick doesn't work

### ISSUE THREAD

**Issue by Ir1d** [ashleve/lightning-hydra-template#218]
Hi,

I'm trying to pass extra config into the instantiate function using the second solution in README: https://github.com/ashleve/lightning-hydra-template#useful-tricks .
But I found that the datamodule config is transformed to datamodule object.
My workaround is to remove the keys containing `_target_`, then the argument is passed fine

**Comment by ashleve** [comment]
Thank you, please add `recursive=False` to instantiation method to prevent recursive object initialisation. I will fix that in the README

**Comment by Ir1d** [comment]
In my case passing `_recursive_=False` doesn't work. I'm not very familiar with hydra. Just posting here for further reference
