### ISSUE TITLE
"optional local: default.yaml" in configs/config.yaml, what is it?

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#221]
May I ask what is it? I thought it was something in configs/local but the folder is pretty empty. Nevertheless the code still runs and I wonder what the optional default.yaml is. Is it automatically ignored?

**Comment by ashleve** [comment]
Please refer to the [#Local Configuration](https://github.com/ashleve/lightning-hydra-template#local-configuration) part of the docs.

The `optional` keyword makes it not necessary for `default.yaml` to exist.
