### ISSUE TITLE
When using comet logger, progress bar is not shown until the end of epoch

### ISSUE THREAD

**Issue by Ir1d** [ashleve/lightning-hydra-template#222]

**Comment by ashleve** [comment]
Thank you for reporting. I think it's a bug in lightning, related to RichProgressBar which is quite new. The progress bar displays correctly if you remove RichProgressBar from default callback configs. I made an [issue about it in pytorch lightning repo](https://github.com/PyTorchLightning/pytorch-lightning/issues/11043)

**Comment by ashleve** [comment]
Seems like the issue is fixed:
https://github.com/PyTorchLightning/pytorch-lightning/issues/11043
