### ISSUE TITLE
include hyperparameter search in experiment?

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#227]
I tried to override a hyperparameter search in experiment.yaml and define my own hparams search in the experiment.yaml file but it gives me an error
<img width="437" alt="image" src="https://user-images.githubusercontent.com/28517073/146137833-8a1b52a1-f563-4445-9c33-b8610008f400.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/28517073/146137963-8435ee1f-dc8c-41d5-9e4e-cba101bf807f.png">

<img width="861" alt="image" src="https://user-images.githubusercontent.com/28517073/146137869-5febe3a1-d8ea-4e7e-9f57-8a41187d1e86.png">

Alternatively, if I do not override it,
<img width="417" alt="image" src="https://user-images.githubusercontent.com/28517073/146138171-83526e78-7c36-4738-8049-93bc4ea3600c.png">

it just used the mimic_optuna.yaml instead of the hyperparam_search I defined in experiment.yaml

**Comment by ashleve** [comment]
`hparams_search` is not a separate config module/part - it's more like a global override of chosen parameters. It's implemented by adding `# @package _global_` at the top of the `mnist_optuna` config file. 

This means you can't override it as module in experiment config - instead, you could simply copy everything from your `mimic_optuna.yaml` directly into the experiment config.

You can read more about it the [Hydra docs](https://hydra.cc/docs/patterns/configuring_experiments/). It's worth looking at common config design patterns.
