### ISSUE TITLE
DDP train, but test on single GPU failed

### ISSUE THREAD

**Issue by zhiyuanpeng** [ashleve/lightning-hydra-template#230]
Hi, I find that when train in DDP mode, the sampler may drop or add data according to `drop_last`, see this [issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/11102). For research project, especially on test data, we can't modify the data.

The solution is to after multi GPU training, use single GPU for testing, here is one [solution](https://github.com/PyTorchLightning/pytorch-lightning/issues/8375) I use.

The code is:

```
    # Test the model
    if config.get("test_after_training") and not config.trainer.get("fast_dev_run"):
        log.info("Starting testing!")
        best_ckpt_path=trainer.checkpoint_callback.best_model_path
        if config.trainer.gpus == -1:
            # close the multi gpus mode
            torch.distributed.destroy_process_group()
            if trainer.is_global_zero:
                config.trainer.gpus=1
                config.trainer.accelerator = None
                trainer: Trainer = hydra.utils.instantiate(config.trainer, callbacks=callbacks, 
                logger=logger, _convert_="partial")
        trainer.test(model=model, datamodule=datamodule, ckpt_path=best_ckpt_path)
```

But it shows error: `Error executing job with overrides: ['experiment=xxx]`, how to solve this problem? Thanks.

**Comment by zhiyuanpeng** [comment]
problem solved by `traine=Trainer(...)`

**Comment by amorehead** [comment]
@zhiyuanpeng, does this solution still work for you with the latest version of Lightning and Hydra? I am using PyTorch 1.10.2, Lightning 1.7.6, and Hydra 1.2, and with this setup (and with DDP as my training `strategy`) I see my training jobs freeze around the call to `torch.distributed.destroy_process_group()`.
