### ISSUE TITLE
load model from checkpoint and also log hyperparameters

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#232]
Currently my workflow is like run.py -> trainer -> (instead of train model, load model from a ckpt file) -> test model

But in this way the model's hyperparameters will not be logged and uploaded to wandb. 

Have you ever had this concern before?

**Comment by ashleve** [comment]
Hi @2533245542, are you sure hyperparameters are not present?

I just did the following:
1. Removed the `trainer.fit` from the `train.py`
2. Run from ckpt with `python run.py logger=wandb trainer.resume_from_checkpoint="/path/lightning-hydra-template/logs/runs/2021-12-27/15-56-45/checkpoints/last.ckpt"`

And the all of the hyperparameters were present in wandb run.

**Comment by 2533245542** [comment]
I see. I was editing run.py to manually skip the training set and load from the checkpoint. Setting the trainer flag is a cleaner way.
