### ISSUE TITLE
optuna tpe sampler samples the same hyperparameters

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#233]
When using Optuna TPE sampler, I found it sometimes samples the same combination of hyperparemters even when the search space is sufficient. Is this a normal scenario?

**Comment by ashleve** [comment]
I'm not sure how the Optuna manages it underneath. I would assume there should be a mechanism preventing the same hyperparameters. Perhaps this occurs only during random trials at the beginning - there's a parameter in the config called `      n_startup_trials: 10`, it means Optuna runs 10 random trials at the beginning, and only after that starts more intelligent hyperparameter sampling.

**Comment by yipliu** [comment]
> When using Optuna TPE sampler, I found it sometimes samples the same combination of hyperparemters even when the search space is sufficient. Is this a normal scenario?

This happened to me too
