### ISSUE TITLE
wandb artifact uploaded only new created files but not edits

### ISSUE THREAD

**Issue by 2533245542** [ashleve/lightning-hydra-template#234]
I found that files edited are not uploaded to wandb and the version of the file is when it was newly created. Does similar thing occurs to you?

**Comment by ashleve** [comment]
Could you elaborate a little more what do you mean by edits?

If you take a look at the `UploadCodeAsArtifact` callback, it creates an artifact only at the beginning of the training:
https://github.com/ashleve/lightning-hydra-template/blob/8b62eef9d0d9c863e88c0992595688d6289d954f/src/callbacks/wandb_callbacks.py#L63-L68

In what situation would you like it to be updated? When running testing after loading from checkpoint? In that case you could modify it to also create artifact at test start.

**Comment by 2533245542** [comment]
Upload the latest code when training is fine. I found it weird because it was uploading the code I edited a few hours ago, not what I edited a few minutes ago. Or is it related to git? I haven't done any git add or commit operation since I downloaded your repository.

**Comment by ashleve** [comment]
> Upload the latest code when training is fine. I found it weird because it was uploading the code I edited a few hours ago, not what I edited a few minutes ago. Or is it related to git? I haven't done any git add or commit operation since I downloaded your repository.

That's weird, if I edit the file (without committing) and run training, then the uploaded code files are correct.

 Perhaps some of your files are ignored in `.gitignore`? The callback doesn't upload files which are ignored.
