### ISSUE TITLE
single gpu is working, but if I run run.py on multiple its giving error FileNotFoundError: [Errno 2] No such file or directory: '/glb/data/drs1/projects/yogesh/AI_at_scale/Benchmark_with_mnist/hydra/lightning-hydra-template/logs/runs/2022-01-04/02-18-41/run.py'

### ISSUE THREAD

**Issue by yogi9879** [ashleve/lightning-hydra-template#240]
FileNotFoundError: [Errno 2] No such file or directory: '/AI_at_scale/Benchmark_with_mnist/hydra/lightning-hydra-template/logs/runs/2022-01-04/02-18-41/run.py'

**Comment by ashleve** [comment]
Have you made sure your hydra and pytorch lightning are recent releases?

Have you made any code changes or just run the template example?

Please provide some info to reproduce the issue
