### ISSUE TITLE
`mode=debug` is not overriding the defaults list when running alongside an experiment config

### ISSUE THREAD

**Issue by mariomeissner** [ashleve/lightning-hydra-template#245]
When I use `python run.py experiment=something mode=debug`, I expect the `trainer` to be overridden by the `debug.yaml` one, but in fact this doesn't happen (looking at the config tree reveals that the `default.yaml` is being used. Additionally, I am also trying to disable loggers and callbacks in this mode, by setting them to `null` or `none.yaml`. However, they are also still being loaded.

I assume that this is because the experiment config also has an `- override /trainer`, but my knowledge of hydra is not enough to figure out why this isn't working.

**Comment by ashleve** [comment]
This is probably because of the order in `config.yaml`
![image](https://user-images.githubusercontent.com/43458894/149663546-a3c35a58-f46c-40ed-ab73-5d019250dd76.png)

Try having experiment before mode

**Comment by mariomeissner** [comment]
Unfortunately that's not working for me.
By the way, an easy way to check the defaults tree is like this:
` train.py experiment=bert_mnli mode=debug.yaml --info defaults-tree`

I tried all possible orders, but the trainer stays as `default.yaml`.

**Comment by mariomeissner** [comment]
Ah, nevermind. As you mention, changing the order in `config.yaml` solves the issue. I was trying to change the order inside the experiment config only.

Thank you!

**Comment by mariomeissner** [comment]
@ashleve I think it should be like that by default though, since it is the user's expectation to switch to debug mode completely when setting this flag.

**Comment by mariomeissner** [comment]
Unfortunately, I just realized this isn't a solution yet.
When changing the order and not specifying any mode in the command line, it breaks because we try to override mode in experiment (no mode is available yet, so it fails).

**Comment by ashleve** [comment]
I guess there's no solution with the current `mode` setup. What do you think about refactoring template to get rid of the `mode' config. We could go with something like this:
```yaml
defaults:
  - log_dir: default.yaml  # alternatively `debug.yaml`
  - experiment: default.yaml 
  - debug: null  # debugging configs, setting default.yaml sets log_dir to debug.yaml

name: "default/${now:%Y-%m-%d}_${now:%H-%M-%S}"
```

No more normal or experiment mode, instead all runs are treated as experiments, with optional `debug` config which can be attached from command line.

Not sure if I haven't missed anything here, I will need to implement be sure it makes sense.

**Comment by mariomeissner** [comment]
I'll happily try it out and PR if I see it works well!

**Comment by mariomeissner** [comment]
While I didn't prepare a PR yet, I tried your new suggested structure and it works well. I can now debug with `debug=default` no matter if I have an experiment file or not.

**Comment by ashleve** [comment]
The new structure has been introduced with https://github.com/ashleve/lightning-hydra-template/pull/248
