### ISSUE TITLE
Requirements don't work with M1 Mac.

### ISSUE THREAD

**Issue by dreaquil** [ashleve/lightning-hydra-template#246]
I have found that creating a new virtualenv and installing the requirements as is throw errors due to incompatibility in the numpy dependency of one of the hydra packages. I changed the requirements to be the following and it works fine:

```
hydra-core>=1.1.0
hydra-colorlog>=1.1.0
hydra-optuna-sweeper>=1.1.0
```

Would it be possible to upgrade these packages?

**Comment by ashleve** [comment]
@dreaquil Thanks, it's upgraded now
