### ISSUE TITLE
Can you share a method for NLP users to deal with Vocab Size?

### ISSUE THREAD

**Issue by yipliu** [ashleve/lightning-hydra-template#271]
Hi,

This is a great template!

However, I have yet to find a way to deal with vocab_size which is derived from datasets and cannot be preset in advance.

Do you know an elegant way to do it?

**Comment by ashleve** [comment]
If you need to access datamodule attributes in the model then it's described in the readme, see [#Useful-Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks) section.

Other than that you can create a different datamodule for each dataset and preset vocabulary size in damodule config, and then access it in model through variable interpolation: `vacab_size: ${datamodule.vocab_size}`.

**Comment by yipliu** [comment]
How careless of me!

Thank you so much!

**Comment by yipliu** [comment]
Hi,

Sorry for the late reply

In [#Useful-Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks) section, does the following code is wrong

```bash
# this will return attribute 'param1' from datamodule object
param1: ${datamodule: param1}
```
That should be
```bash
# this will return attribute 'param1' from datamodule object
param1: '${datamodule: param1}'
```

**Comment by ashleve** [comment]
Thanks for noticing. 

Alternatively you can also just omit the space between `datamodule:` and `param1`:
`param1: ${datamodule:param1}`

Fixed the readme with https://github.com/ashleve/lightning-hydra-template/pull/279.

**Comment by yipliu** [comment]
Hi,

Can you add more detailed information for this trick?
```python
# ./src/datamodules/my_datamodule.py
from omegaconf import OmegaConf

class MyDataModule(LightningDataModule):
	def __init__(self, param1):
		super().__init__()

		self.vocal_size= self.get_vocab_from_data() 

		resolver_name = "datamodule"
		OmegaConf.register_new_resolver(
			resolver_name,
			lambda name: getattr(self, name),
			use_cache=False
		)
	def get_vocab_from_data(self):
		pass
```
This obvious form is more useful for NLPer.

**Comment by yipliu** [comment]
@ashleve Hi

When I use the [#Useful-Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks) with hparams_search, it occurs the following error

>ValueError: Error instantiating 'src.datamodules.MyDataModule': resolver 'datamodule' is already registered

**Comment by yipliu** [comment]
Hi @ashleve 

When I used [#Useful-Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks) with hyparams_search, it occurred an error with **resolver is already registered hydra**. 

Luckily, I find a good solution in [this](https://github.com/facebookresearch/hydra/issues/861#issuecomment-675828402). We also can strengthen our code by adding a line code

```python
# ./src/datamodules/my_datamodule.py
from omegaconf import OmegaConf

class MyDataModule(LightningDataModule):
	def __init__(self, param1):
		super().__init__()

		self.vocal_size= self.get_vocab_from_data() 
                
                if OmegaConf.get_resolver("my_custom_resolver") is None:
		         resolver_name = "datamodule"
		         OmegaConf.register_new_resolver(
			              resolver_name,
			              lambda name: getattr(self, name),
			             use_cache=False
		           )
	def get_vocab_from_data(self):
		pass
```

Would you mind adding this line  in [#Useful-Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks)
