### ISSUE TITLE
Changing DataModule Attributes per Epoch

### ISSUE THREAD

**Issue by barisbatuhan** [ashleve/lightning-hydra-template#278]
Due to my training pipeline, my data module requires changing some of its attributes per each epoch. However, I could not understand how I can reach the data module object from my LightningModule model. Is there any way to manipulate data parameters from the model object?

**Comment by ashleve** [comment]
It's possible to pass datamodule or other related object directly to lightning module on init, take a look at [# Useful Tricks](https://github.com/ashleve/lightning-hydra-template#useful-tricks) readme section.

According to [this issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/4607), you could also write a custom callback that modifies datamodule every epoch:
```python
class Scheduler(pl.Callback):
    def _prepare_epoch(self, trainer, model, epoch):
        phase = ... 
        trainer.datamodule.set_phase(phase)

    def on_epoch_end(self, trainer, model):
        self._prepare_epoch(trainer, model, trainer.current_epoch + 1)
```

Remeber to also set `reload_dataloaders_every_n_epochs=1` in trainer.
