### ISSUE TITLE
Possibility of getting the results of multiple seeds logged to one run

### ISSUE THREAD

**Issue by nghiahhnguyen** [ashleve/lightning-hydra-template#283]
If I want to run the same config with multiple seeds (eg., 50 seeds), is there a way to get the results logged to just a single run?

From reading the pipeline code, I see that I can only get a run (with a separate seed) at a time. Then I can try to aggregate 50 runs' results together. However, with such a large number of runs, it gets hard to manage the list of runs.

Can I use multirun for this? I see some potential, but I'm not sure how multirun works exactly.

**Comment by ashleve** [comment]
Last time I checked no logger supported logging many experiments into a single run. But there are some loggera which allow for averaging the results from chosen experiments.

So I think you have two options.

1. Launch a multirun for all seeds and aggregate the results using some logger

    For example, you could launch the multirun with wandb logger for 50 different seeds like this:
    ```bash
    python run.py -m seed=range(1,50) logger.wandb.group="experimentX"
    ```
    And then use the wandb UI to average the results of all experiments from group "experimentX". 
    
    You could also launch this multirun with csv logger and then write custom scripts for parsing the csv results from `logs` folder.

2. Write a custom pipeline that launches 50 experiments one after the other, copy and store results from logger after each experiment.

**Comment by nghiahhnguyen** [comment]
Thank you for your suggestions!
