### ISSUE TITLE
best practice for datamodule trainable models

### ISSUE THREAD

**Issue by tomerperetz** [ashleve/lightning-hydra-template#284]
What is the best practice for using trainable models in datamodule, i.e. standard scalers?
I would like to be able to export them with the checkpoint, and use them again in tests or inference.

**Comment by ashleve** [comment]
Could you elaborate on what you mean by using model in datamodule?

I always thought standard scalars are usually either computed at the beginning of the run or loaded from a variable.

**Comment by tomerperetz** [comment]
yes sure.

I'm using standard scalers, and mini rocket embeddings [(),](https://github.com/angus924/minirocket) 
both need to be fitted: standard scalers are calculated, and mini rocket drills weights.
fitting is executed only on the train set, and both need to be used on valid, test, and inference, along with the trained deep learning model.

my current workaround was adding explore section into the training set, but I think it should be saved in the same manner as saving the model ckpt.

**Comment by ashleve** [comment]
@tomerperetz I'm not sure if I understand correctly, but I assume your data needs to be additionally transformed after loading the model, depending on some values stored in the checkpoint.

Maybe you could add something like this to your LightningModule code?
```python
    def on_save_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        checkpoint["scalers"] = self.scalers
        return super().on_save_checkpoint(checkpoint)

    def on_load_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        self.trainer.datamodule.transform_data(checkpoint["scalers"])
        return super().on_load_checkpoint(checkpoint)
```

**Comment by tomerperetz** [comment]
works great, thank you
