### ISSUE TITLE
Wandb is not compatible with PL 1.6.1

### ISSUE THREAD

**Issue by yipliu** [ashleve/lightning-hydra-template#285]
Hi,

There may be version conflict between wandb and PL 1.6.1

**OS:** Ubuntu20.04
**Python:** 3.8.13
**Pytorch:**  1.11.0
**PL:** 1.6.1
**Wandb:** 0.12.11
**hydra-core:** 1.1.2

when I use the Hyperparameter Search, it produces the following error:

```python
FileNotFoundError: [Errno 2] No such file or directory: '/**/logs/experiments/multiruns/**/time/0/wandb/offline-run-20*/logs/debug-internal.log'
Problem at: /home/*/anaconda3/envs/*/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py 357 experiment
```

**Comment by Gxinhu** [comment]
I have met the same problem.

**Comment by yipliu** [comment]
> I have met the same problem.

Install PL=1.5.10

**Comment by johnnynunez** [comment]
for me it's working with 1.6.3 
only update wandb 0.12.16
