### ISSUE TITLE
wandb log only 1 run when using ddp and multirun

### ISSUE THREAD

**Issue by OZOOOOOH** [ashleve/lightning-hydra-template#289]
When I use DDP, wandb and multirun in `test.py` like this 
`python test.py -m ckpt_path='~~' +seed=1,2,3 +trainer.strategy=ddp logger=wandb`
Wandb does not record 3 runs, but only one run.

**Comment by ashleve** [comment]
Try adding `wandb.finish()` at the end to make sure it has closed properly
