### ISSUE TITLE
An easy way to find the  val_acc_best, when set wandb.offline=True

### ISSUE THREAD

**Issue by yipliu** [ashleve/lightning-hydra-template#290]
Hi, 

When I use **hyperparameter searches**, I can find the best *val_acc_best* in *optimization_results.yaml*.

However, when I use **python train.py experiment=experiment.yaml**, I can not find where the result of *val_acc_best* is.

I know that when set wandb.offline=False, I can find 'wand-summay.json' which recorded all results in detail. However, when I set wandb.offline=True, there was nothing but {"_wandb": {"runtime": 154}}.

I wanted to find an easy way to show the **val_ACC_best** results locally when I set wandb.offline=True.

**Comment by ashleve** [comment]
You can use csv logger simultaneously with wandb logger if you need to access the metric values in easy to use format.

As for wandb, the offline mode still requires you to upload the generated `.wandb` file to either the cloud or local wandb instance to read the results.

**Comment by yipliu** [comment]
Thank You
