### ISSUE TITLE
Evaluation + Direct Storage

### ISSUE THREAD

**Issue by johnnynunez** [ashleve/lightning-hydra-template#292]
FYI Dali:
Nvidia has enabled its DirectStorage technology (RTX IO), which allows data to be loaded directly from the NVME SSD directly to the GPU(VRam). This allows for solving the current data transfer bottleneck, saving CPU resources, and freeing up space in RAM
DALI supports GPU Direct Storage functionality through[ the numpy reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.numpy). To utilize it with any framework DALI support, create a pipeline and wrap it into a[ corresponding iterator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/framework_plugins.html). To use the GPU Direct Storage itself please enable it according to[ its documentation](https://developer.nvidia.com/gpudirect-storage). From the DALI side, there is no constraint regarding GPU direct support, from Nvidia Turing, including Ampere, they are fully compatible, (Serie 2000 and 3000)
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-lightning.html

Question:
How could I automatize from X models trained to evaluate without having to put the path of the each saved models?
For example,
I have 25 trained models, and I generate metrics to store in dataframe, but it is very cumbersome to have to put the path of each model.

**Comment by ashleve** [comment]
The way I usually approach such problems is:

1. I execute the runs with some marker to make them easier to identify, e.g. `python train.py +tags=["tag1", "tag2"]
2. I write a script or notebook to search over the `logs/` directory and retrieve all runs that meet the specified criteria
3. Then I either write a pipeline that executes extra evaluations on all ckpts one by one, or construct a multirun command that iterates over ckpts

**Comment by johnnynunez** [comment]
thanks! In the end I have done it, by making a script.
