### ISSUE TITLE
Support M1 ARM

### ISSUE THREAD

**Issue by johnnynunez** [ashleve/lightning-hydra-template#302]
This has been released today
https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/ 
https://github.com/PyTorchLightning/pytorch-lightning/issues/13102

**Comment by johnnynunez** [comment]
Now @ashleve PL is supporting installing pull request.
Download zip from https://github.com/PyTorchLightning/pytorch-lightning/tree/mps_accelerator
pip install pytorch-lightning-mps_accelerator.zip

**Comment by johnnynunez** [comment]
solved https://github.com/ashleve/lightning-hydra-template/issues/308#issuecomment-1138752897

**Comment by sldcyh** [comment]
> Now @ashleve PL is supporting mac accelerator installing pull request. Download zip from https://github.com/PyTorchLightning/pytorch-lightning/tree/mps_accelerator pip install pytorch-lightning-mps_accelerator.zip

Thanks! This solved my problem for now.

**Comment by johnnynunez** [comment]
@sldcyh look still the limitations on MPS.
https://github.com/pytorch/pytorch/issues/77764#issuecomment-1162891798
