### ISSUE TITLE
hyper-paramaeter search raise ValueError(f"resolver '{name}' is already registered")

### ISSUE THREAD

**Issue by huidiwiwi** [ashleve/lightning-hydra-template#310]
Hi, great template. 
I'm currently facing a problem when run hyper-paramas search 
I need to access the datamodule object attributes when instantiation model. I have tested the 3. method shown in Useful Tricks for Accessing datamodule attributes in model. It works by a single run, but ends up getting the error after the first run.
Do you have any advice? thanks a lot!

**Comment by ashleve** [comment]
Try adding this to `utils.finish()`:
```python
from omegaconf import OmegaConf

Omegaconf.clear_resolvers()
```

**Comment by huidiwiwi** [comment]
Wow! Thanks a lot for your quick response. I also found another workaround solution by adding replace=True in register_new_resolver().
`OmegaConf.register_new_resolver(
    resolver_name,
    lambda name: getattr(self, name),
    replace=True,
    use_cache=False)`

> Try adding this to `utils.finish()`:
> 
> ```python
> from omegaconf import OmegaConf
> 
> Omegaconf.clear_resolvers()
> ```
