### ISSUE TITLE
test_debug_overfit FAILED  

### ISSUE THREAD

**Issue by huidiwiwi** [ashleve/lightning-hydra-template#314]
Hi, It seems like pytorch lightning has disabled validation when using Trainer flag `overfit_batches`
["If nonzero, will turn off validation."](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#overfit-batches)
when tesing debug=overfit, it raise RuntimeError: Early stopping conditioned on metric `val/acc` which is not available.
I tried adding this in configs/debug/overfit.yaml. but it didn't help
`
callbacks:
    - early_stopping: None
`
also tried this, receive " Cannot merge DictConfig with ListConfig full_key: object_type=dict  "
`
callbacks:
  early_stopping:
    - none.yaml`

**Comment by ashleve** [comment]
Will fix that in the next release

For now you could just overwrite the monitored metric in `overfit.yaml`
```yaml
callbacks:
  early_stoppping:
    monitor: "train/acc"
```

**Comment by huidiwiwi** [comment]
> Will fix that in the next release
> 
> For now you could just overwrite the monitored metric in `overfit.yaml`
> 
> ```yaml
> callbacks:
>   early_stopping:
>     monitor: "train/acc"
> ```

Thanks a lot. But I still get the same RuntimeError that val/acc is not available, it seems like the early stopping config is not overwritten in callbakcs conf. I tried add the full snippets of early_stopping, now it works!

**Comment by ashleve** [comment]
Take a look at the config printed during run to see if the monitored metric is overwritten. If you didn't make a typo in the config then executing `python train.py debug=overfit` should overwrite the metric
