### ISSUE TITLE
error instance MLflowLogger - v1.4 repo

### ISSUE THREAD

**Issue by johnnynunez** [ashleve/lightning-hydra-template#325]
I don't use this to train, but breaks in my training
version: v1.4
![image](https://user-images.githubusercontent.com/22727137/171287487-eae2bd2b-c4b0-4417-90ef-ea0f75fd6a44.png)

**Comment by johnnynunez** [comment]
FIIXED: MLFlowLogger RENAMED:
![image](https://user-images.githubusercontent.com/22727137/171288134-0c09af79-6ae2-41ed-8acf-a27bf30a7609.png)

**Comment by ashleve** [comment]
@johnnynunez Thanks! feel free to make a PR in such situations
