### ISSUE TITLE
Hidden error trace by hydra

### ISSUE THREAD

**Issue by ljhgabe** [ashleve/lightning-hydra-template#350]
Hi @ashleve, sorry if my question sounds dumb since i am very new to hydra but I am quite confused about hydra's behaviour of hiding the error trace for compilation error. For example:
```
[2022-06-08 08:12:42,389][src.training_pipeline][INFO] - Instantiating datamodule <src.datamodules.xxx_datamodule.XXXDataModule>
[2022-06-08 08:12:42,395][src.training_pipeline][INFO] - Instantiating model <src.models.xxx_module.XXXLitModule>
Error executing job with overrides: []
Error locating target 'src.models.xxx_module.XXXLitModule', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
From this error message I thought I did not set the correct paths in configs at first. But after replacing the hydra's instantiate statement with the hard-coded one (i.e. model = XXXLitModule()), the error suggest that I haven't downloaded a package that was used in the script. The full stack trace cannot be shown even though I set the `HYDRA_FULL_ERROR` to 1, I wonder if there is any way I can get a more accurate error message instead of a very confusing one? (like `Error locating target...` )

Thanks

**Comment by ashleve** [comment]
@ljhgabe Full stack trace should appear if you execute with:
```
HYDRA_FULL_ERROR=1 python train.py
```
Have you tried this?

Your error simply indicates that the module class was not found
```
Error locating target 'src.models.xxx_module.XXXLitModule'
``` 
Maybe typo in the `_target_` path in the config?

**Comment by ljhgabe** [comment]
> @ljhgabe Full stack trace should appear if you execute with:
> 
> ```
> HYDRA_FULL_ERROR=1 python train.py
> ```
> 
> Have you tried this?
> 
> Your error simply indicates that the module class was not found
> 
> ```
> Error locating target 'src.models.xxx_module.XXXLitModule'
> ```
> 
> Maybe typo in the `_target_` path in the config?

HI @ashleve, thanks for the reply!

I tried to execute again with
`HYDRA_FULL_ERROR=1 python train.py`
and I think it worked.

Previously I my command was 
`python train.py +HYDRA_FULL_ERROR=1`
and I think this was probably why I could not get the full stack trace.

Thanks
