### ISSUE TITLE
Question: The training log epoch's number is not consistent with the validation log epoch's number in CSV Logger

### ISSUE THREAD

**Issue by ZJZ1223** [ashleve/lightning-hydra-template#361]
![image](https://user-images.githubusercontent.com/71306074/176480666-f7836cc1-1ecf-4a25-8799-cfa00901ebfe.png)

**Comment by ZJZ1223** [comment]
As shown in the figure, I think that val log epoch number should be alinged with training epoch number , or I miss something?please help me figure out that.

**Comment by ashleve** [comment]
@ZJZ1223 I just executed the main branch with `python train.py logger=csv` and my epoch numbers seem to be correct:
![image](https://user-images.githubusercontent.com/43458894/177213833-3a7e972f-5c96-4289-a25a-cb0022bae0e9.png)

I'm guessing some modifications in your code have caused this. 

You could try upgrading the libraries or the new template release which has not been merged yet: https://github.com/ashleve/lightning-hydra-template/issues/308

**Comment by ZJZ1223** [comment]
@ashleve Thank you so much, it solves my problems.
