### ISSUE TITLE
`train.log` and `eval.log` are generated in current work dir

### ISSUE THREAD

**Issue by ashleve** [ashleve/lightning-hydra-template#396]
Currently `train.log` and `eval.log` are generated in current working directory.

This issue has been already fixed by hydra devs and will disappear when the new `hydra-colorlog` package version is released
https://github.com/facebookresearch/hydra/pull/2242

For now you can simply disable `hydra-colorlog` in hydra config to prevent the issue.

**Comment by zcx-language** [comment]
I find that the lightning console log cannot write to train.log.
I want to log the model architecture (use ModelSummary callback) into train.log, but it cannot.

Console Outputs:
![image](https://user-images.githubusercontent.com/38426607/189013179-a7701b4f-052e-4161-9b54-9814a2f4c98b.png)

train.log Outputs:
![image](https://user-images.githubusercontent.com/38426607/189013302-2547782b-43a3-486a-ae89-3bb8d3c2ab89.png)

It can be found that the lightning logs only print to the console, how can I fix this problem? Thanks.
