### ISSUE TITLE
Multi-GPUs without DDP for hparams_search

### ISSUE THREAD

**Issue by ker2xu** [ashleve/lightning-hydra-template#415]
It seems that current template only supports using multi-GPUs with DDP (Distributed Data Parallel), which means that multi-GPUs run with one common set of hyper-parameters. Is it possible to use multi-GPU in a way such that each GPU runs with a different set of hyper-parameters? 
I tried to modify "devices: 1" to "devices: 4" in the gpu.yaml but I saw that hydra searched for hyper-parameters 8 times instead of twice when I set "n_trials: 8" in the "mnist_optuna.yaml".
Many thanks!

**Comment by ashleve** [comment]
I think what you're looking for is running parallel jobs on a cluster.

You should take a look at the launchers available in hydra, like `joblib` or `submitit`:
https://hydra.cc/docs/plugins/joblib_launcher/
https://hydra.cc/docs/plugins/submitit_launcher/

I have not verified it works with this template

**Comment by ker2xu** [comment]
Thanks for your reply! I will check those.
