### ISSUE TITLE
Environment variable 'PROJECT_ROOT' not found

### ISSUE THREAD

**Issue by cpoptic** [ashleve/lightning-hydra-template#418]
When running `python src/my_main.py`, which contains the hydra decorated function:

```
@hydra.main(version_base=None, config_path="configs/", config_name="train.yaml")
def func(cfg: DictConfig):
    print(OmegaConf.to_yaml(cfg))
```

I get an error message:

`    raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'PROJECT_ROOT' not found"
    full_key: hydra.run.dir
    object_type=dict`

What and where should the `PROJECT_ROOT` be specified?

**Comment by ashleve** [comment]
PROJECT_ROOT is an environment variable containing absolute path to the project root.

Normally it is inferred and set automatically with this line:
https://github.com/ashleve/lightning-hydra-template/blob/9e7089ce70dac66096576c6596e966d4c38cbdce/src/train.py#L8-L14

Do you have it in your entry file?

**Comment by cpoptic** [comment]
Ah, yes I had not included that line. It's working now, thank you
