### ISSUE TITLE
Can I make pull request for Vertex AI hyperparameter tuning job?

### ISSUE THREAD

**Issue by Yongtae723** [ashleve/lightning-hydra-template#432]
Hello! Łukasz Zalewski !

Thank you for the Truly fantastic code of lightning-hydra-template.
I learned a lot from this code and was very impressed!

We created [a new template code](https://github.com/jxpress/lightning-hydra-template-vertex-ai) that can run your template code on Vertex AI, based on this repository.

Since there is a compatibility issue between Hydra and Vertex AI, so your code could not be run as is in Vertex AI and required some minor modifications. Please see [our blog](https://github.com/jxpress/lightning-hydra-template-vertex-ai/blob/main/documents/translated_blog.md) for more details.

I guess you don't want to complicate the code, so I didn't do a pull request or anything, but if you want to merge, please let me know and I'll do that.

Thank you for publishing this really great code!

**Comment by Yongtae723** [comment]
Or can I make it one branch of this repository?

If I can do that, it would be easier to merge it when your code is updated!

**Comment by ashleve** [comment]
Hi @Yongtae723 

Thank you for using the project! 

I am not familiar with vertex AI but it's nice to see template being integrated for different use cases.

As for merging the changes, we're trying to keep the template minimalistic and general, so I'd prefer not to introduce very specific use cases to the codebase.

It would be great though to mention your Vertex AI hyperparameter search integration under [# Resources / useful repositiories](https://github.com/ashleve/lightning-hydra-template#resources), feel free to make a readme PR if you'd like to!

**Comment by Yongtae723** [comment]
Hi @ashleve 

Thank you for your reply and suggestion!
I will make a readme PR as soon as possible!

thank you
