### ISSUE TITLE
Load PL checkpoint to the native torch.nn.Module used to init the `XLitModule` (e.g.,MNISTLitModule)

### ISSUE THREAD

**Issue by bwdeng20** [ashleve/lightning-hydra-template#447]
Suppose I write a `GNNLitModule` like MNISTLitModule, which requires the first argument to be a model instance (let's say the model class name is `GNNNATIVE` such that `gnn=GNNNATIVE()`)
```python3
class GNNLitModule(pl.LightningModule):
    def __init__(
        self,
        gnn: torch.nn.Module,
        optimizer: Any = None,
    ):
        super().__init__()
        self.save_hyperparameters(logger=False, ignore=["gnn"])
        self.gnn = gnn
```
After training and saving, I can load a PL checkpoint dict as follows.
![image](https://user-images.githubusercontent.com/26434203/191889538-a65578d6-cb46-4786-a3e6-305aa2bf5911.png)

Now how can I load the `state_dict` into another `GNNNATIVE ` instance?

**Comment by ashleve** [comment]
@bwdeng20 Apologies for the delayed answer. 

I'm not sure if I understand the problem.

According to pytorch docs, you can load state dict with:
```python
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
```

Have you managed to resolve the issue?

**Comment by bwdeng20** [comment]
Never mind. I've solved this problem.
The original post is to ask for an elegant practice to load a trained PL checkpoint (saved by `module=MNISTLitModule(model, optimizer)`) to the actual native torch `model` by adding a method that removes the prefix added by `module`.

```python3
    def load_th_or_pl_ckpt2md(model: torch.nn.Module, ckpt=None):  # TODO
        if ckpt is None:
            warnings.warn(f"No checkpoint is loaded for {type(model)}!")
            return model

        loaded = torch.load(ckpt)
        model_state_dict = loaded["state_dict"]
        is_ckpt_lit = "pytorch-lightning_version" in loaded
        if is_ckpt_lit:
            state_dict_wo_prefix = {
                k.split(".", 1)[1]: v for k, v in model_state_dict.items()
            }
        else:
            state_dict_wo_prefix = model_state_dict
        assert isinstance(state_dict_wo_prefix, Mapping)
        model.load_state_dict(state_dict_wo_prefix)
        return model
```
