### ISSUE TITLE
Overloading training_epoch_end may not be a good idea without an explicit warning

### ISSUE THREAD

**Issue by byfron** [ashleve/lightning-hydra-template#458]
I've been tracking what I thought was a memory leak, and eventually I figured out that when overriding training_epoch_end, under the hood pytorch-lightning accumulates every result for every single batch of the epoch. This may not be an issue when training on mnist but when dealing with larger datasets (and larger models) it's easy to run into out-of-memory errors. 

My suggestion would be to drop the override in the template (as it can be misleading) or displaying a user warning somewhere.

**Comment by ashleve** [comment]
Thank you for pointing this out! This should definitely be explained explicitly.

I think adding an appropriate comment in `training_epoch_end()` would be most valuable as the template also serves as an educational resource.
