### ISSUE TITLE
Set a random seed when running the `eval.py`

### ISSUE THREAD

**Issue by zcx-language** [ashleve/lightning-hydra-template#518]
I think it needs to set a fixed seed for the random generator during evaluation, just as `train.py` do

**Comment by ashleve** [comment]
hey @zcx-language, why do you think setting a fixed seed for the random number generators is necessary during evaluation, like `train.py` does?

**Comment by zcx-language** [comment]
n my tasks, a random warp-perspective augmentation should be added before feeding images into the neural network during the evaluation phase. If I use a fixed seed, the results could be the same when evaluating a specific checkpoint. 

I have also noticed that the test results obtained from executing `train.py` with `test=true` are inconsistent with the results obtained from reusing `eval.py` on the best checkpoint. I am currently unable to determine whether this is due to an error in my code or some other cause。

**Comment by ashleve** [comment]
Closing this since I assume the problem has been resolved in this issue: https://github.com/ashleve/lightning-hydra-template/issues/527
