### ISSUE TITLE
INFO logging 

### ISSUE THREAD

**Issue by Moadab-AI** [ashleve/lightning-hydra-template#528]
I notice when I run train.py for example there is always a file named "train.log" in the working directory and not "log_dir" specified in path containing all the INFO level output messages. this happens regardless of which and how many loggers i specify ion configs and I cant figure which part of the code specifies creation of this particular log file in the current working directory and outside all of other loggings...

**Comment by ashleve** [comment]
Yes, here's the related issue: https://github.com/ashleve/lightning-hydra-template/issues/396

This was already fixed by hydra but `hydra-colorlog` version with the fix has not been released yet
