### ISSUE TITLE
How to instantiate a child class which inherited from super class?

### ISSUE THREAD

**Issue by zf223669** [ashleve/lightning-hydra-template#529]
Hi,
I have a child class that is inherited from a superclass, the superclass and the child class both have different parameters in init function.
how could I construct the yaml and instantiate the child class? such as:
`class A:
init(var1, var2):
....

class B(A):
init(var3, var4):
super.__init()
......`

**Comment by ashleve** [comment]
Not sure if I undertand you correctly, but the parent class shouldn't matter for instantiation process. Just instantiate the `B` class the same way as all the other objects in this template.

cfg:
```yaml
_target_: path.to.class.B
var1: ...
var2: ...
var3: ...
var4: ...
```

class:
```python
class B(A):
    self.__init__(var1, var2, var3, var4)
        super.__init__(var1=var1, var2=var2)
```

**Comment by zf223669** [comment]
> 

Thank you!
