### ISSUE TITLE
How to use multiple logger to log msg to a file and wandb?

### ISSUE THREAD

**Issue by slyviacassell** [ashleve/lightning-hydra-template#530]
I just want to use multiple loggers to log the msg to different places. Can anybody give me some suggestions?

**Comment by slyviacassell** [comment]
Solved. The pytorch-lightning has a solution for multiple loggers.

**Comment by ashleve** [comment]
Here'a a config for multiple loggers:
https://github.com/ashleve/lightning-hydra-template/blob/main/configs/logger/many_loggers.yaml

`python train.py logger=many_loggers`

**Comment by slyviacassell** [comment]
Thanks for your reply! I will try it.
