### ISSUE TITLE
Question: `_self_` at the end of `defaults` list

### ISSUE THREAD

**Issue by shenoynikhil** [ashleve/lightning-hydra-template#544]
This is just a question and not a feature/bug request. In the [callbacks config](https://github.com/ashleve/lightning-hydra-template/blob/main/configs/callbacks/default.yaml), How does having `_self_`, in the end over [here](https://github.com/ashleve/lightning-hydra-template/blob/ed7dea4718dc9a993cdf5d7d604245b444bac377/configs/callbacks/default.yaml#L6) allow for overriding? I was facing a bug when it was at the top of the list.

**Comment by ashleve** [comment]
It determines the order in which configs override each other.

If `_self_` is at the beginning, then the config fields specified in `callbacks/default.yaml` will be overriden by the same config fields specified in subconfigs attached in the defaults list.

**Comment by shenoynikhil** [comment]
That makes sense!
