### ISSUE TITLE
Update to PyTorch Lightning 2.0

### ISSUE THREAD

**Issue by ucasqsl** [ashleve/lightning-hydra-template#547]
I noticed that the repo currently does not support PyTorch Lightning 2.0, which was recently released. PyTorch Lightning 2.0 has several new features and improvements that could benefit users of this repo.

Could you please consider updating the repo to support PyTorch Lightning 2.0? I think this would be a valuable addition to the project and would help users take advantage of the latest PyTorch Lightning features.

Thank you for your consideration.

**Comment by ashleve** [comment]
This is not yet merged, but a working, updated template is currently on this branch: 
https://github.com/ashleve/lightning-hydra-template/tree/dev

PR: https://github.com/ashleve/lightning-hydra-template/pull/545

(you can already use it)

Will merge soon after adding a couple small improvements.
