### ISSUE TITLE
please support dynamically selecting config_name

### ISSUE THREAD

**Issue by YChienHung** [ashleve/lightning-hydra-template#632]
I want to use the function of dynamically selecting config_name. 

Can this function be added in future versions?

**Comment by qinghuannn** [comment]
Seems that hydra does not support dynamically selecting config_name. [https://github.com/facebookresearch/hydra/issues/2868#issue-2174224596](https://github.com/facebookresearch/hydra/issues/2868#issue-2174224596)

**Comment by SagiPolaczek** [comment]
What do you mean by "dynamically"? 

1. You can specify the config name in the CLI (as I comment in the quoted issue).

2. You can also use the following: https://hydra.cc/docs/advanced/unit_testing/
Which let you specify the config_name inside the python function (that's how I test functions that were wrapped with hydra's api).

**Comment by YChienHung** [comment]
> What do you mean by "dynamically"?
> 
> 1. You can specify the config name in the CLI (as I comment in the quoted issue).
> 2. You can also use the following: https://hydra.cc/docs/advanced/unit_testing/
>    Which let you specify the config_name inside the python function (that's how I test functions that were wrapped with hydra's api).

Could you give me  a link for solution 1 ?  thanks !

**Comment by SagiPolaczek** [comment]
> > What do you mean by "dynamically"?
> > 
> > 1. You can specify the config name in the CLI (as I comment in the quoted issue).
> > 2. You can also use the following: https://hydra.cc/docs/advanced/unit_testing/
> >    Which let you specify the config_name inside the python function (that's how I test functions that were wrapped with hydra's api).
> 
> Could you give me a link for solution 1 ? thanks !

Sure, [here](https://github.com/facebookresearch/hydra/issues/2868#issuecomment-2025141014)

**Comment by YChienHung** [comment]
> > > What do you mean by "dynamically"?
> > > 
> > > 1. You can specify the config name in the CLI (as I comment in the quoted issue).
> > > 2. You can also use the following: https://hydra.cc/docs/advanced/unit_testing/
> > >    Which let you specify the config_name inside the python function (that's how I test functions that were wrapped with hydra's api).
> > 
> > 
> > Could you give me a link for solution 1 ? thanks !
> 
> Sure, [here](https://github.com/facebookresearch/hydra/issues/2868#issuecomment-2025141014)

thank you so much !
