### ISSUE TITLE
If there is a docker image that include environment of this great project that would be great!

### ISSUE THREAD

**Issue by LuoXin-s** [ashleve/lightning-hydra-template#97]

**Comment by sfasdas** [comment]
So as I search for a great engineering considered practice, I finally found this lightning + hydra combinationI, and plan to use this template for a docker context. I wondering if there already have lightning + hydra image in Internet, but I have not find that. If you can provide a docker image contain environment that this template need, this template may be used more easier.

**Comment by hobogalaxy** [comment]
Thank you for using the project!

I was already planning to add dockerfile to the template and upload image. Currently I'm busy with other features but docker support will be here sooner or later.

**Comment by sfasdas** [comment]
Thank you for your quickly response!

**Comment by ashleve** [comment]
@LuoXin-s docker support added.
https://github.com/ashleve/lightning-hydra-template#whale-docker
